# Generated by Django 4.1.3 on 2022-11-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e2w_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='activity',
            name='vehicle',
            field=models.CharField(choices=[('foot', 'foot'), ('bike', 'bike'), ('scooter', 'scooter')], default='bike', max_length=100),
        ),
    ]
